<?php

return [
    'permissions' => [
        'dashboard.view' => ['name' => 'Ver datos gráficos', 'module' => 'Inicio', 'legacy_form_id' => 1],
        'cash.manage' => ['name' => 'Gestionar arqueo de caja', 'module' => 'Caja', 'legacy_form_id' => 2],
        'purchases.create' => ['name' => 'Registrar compras', 'module' => 'Compras', 'legacy_form_id' => 3],
        'purchases.view' => ['name' => 'Consultar historial de compras', 'module' => 'Compras', 'legacy_form_id' => 4],
        'purchases.update' => ['name' => 'Modificar compras', 'module' => 'Compras', 'legacy_form_id' => 4],
        'purchases.cancel' => ['name' => 'Anular compras', 'module' => 'Compras', 'legacy_form_id' => 4],
        'purchases.payments' => ['name' => 'Gestionar pagos de compras', 'module' => 'Compras', 'legacy_form_id' => 5],
        'sales.create' => ['name' => 'Registrar ventas', 'module' => 'Ventas', 'legacy_form_id' => 6],
        'sales.view' => ['name' => 'Consultar historial de ventas', 'module' => 'Ventas', 'legacy_form_id' => 7],
        'sales.update' => ['name' => 'Modificar ventas', 'module' => 'Ventas', 'legacy_form_id' => 7],
        'sales.cancel' => ['name' => 'Anular ventas', 'module' => 'Ventas', 'legacy_form_id' => 7],
        'sales.return' => ['name' => 'Registrar devoluciones', 'module' => 'Ventas', 'legacy_form_id' => 7],
        'sales.payments' => ['name' => 'Gestionar pagos de ventas', 'module' => 'Ventas', 'legacy_form_id' => 8],
        'inventory.view' => ['name' => 'Consultar inventario', 'module' => 'Almacén', 'legacy_form_id' => 9],
        'inventory.products.manage' => ['name' => 'Gestionar productos', 'module' => 'Almacén', 'legacy_form_id' => 10],
        'inventory.categories.manage' => ['name' => 'Gestionar categorías', 'module' => 'Almacén', 'legacy_form_id' => 11],
        'inventory.adjustments.manage' => ['name' => 'Gestionar ajustes', 'module' => 'Almacén', 'legacy_form_id' => 12],
        'inventory.presentations.manage' => ['name' => 'Gestionar presentaciones', 'module' => 'Almacén', 'legacy_form_id' => 13],
        'inventory.lines.manage' => ['name' => 'Gestionar líneas', 'module' => 'Almacén', 'legacy_form_id' => 14],
        'inventory.lots.manage' => ['name' => 'Gestionar lotes', 'module' => 'Almacén', 'legacy_form_id' => 15],
        'expenses.reasons.manage' => ['name' => 'Gestionar motivos de gasto', 'module' => 'Gastos', 'legacy_form_id' => 16],
        'expenses.manage' => ['name' => 'Gestionar gastos', 'module' => 'Gastos', 'legacy_form_id' => 17],
        'data.clients.manage' => ['name' => 'Gestionar clientes', 'module' => 'Datos maestros', 'legacy_form_id' => 18],
        'data.laboratories.manage' => ['name' => 'Gestionar laboratorios', 'module' => 'Datos maestros', 'legacy_form_id' => 19],
        'data.personal.manage' => ['name' => 'Gestionar personal', 'module' => 'Datos maestros', 'legacy_form_id' => 20],
        'data.positions.manage' => ['name' => 'Gestionar cargos', 'module' => 'Datos maestros', 'legacy_form_id' => 21],
        'data.company.manage' => ['name' => 'Gestionar empresa', 'module' => 'Datos maestros', 'legacy_form_id' => 22],
        'users.roles.manage' => ['name' => 'Gestionar grupos de usuarios', 'module' => 'Usuarios', 'legacy_form_id' => 23],
        'users.manage' => ['name' => 'Gestionar usuarios', 'module' => 'Usuarios', 'legacy_form_id' => 24],
        'users.permissions.manage' => ['name' => 'Asignar permisos', 'module' => 'Usuarios', 'legacy_form_id' => 25],
        'reports.view' => ['name' => 'Acceder al módulo de reportes', 'module' => 'Reportes', 'legacy_form_id' => 26],
        'reports.generate' => ['name' => 'Generar reportes', 'module' => 'Reportes', 'legacy_form_id' => 26],
    ],
    'route_permissions' => [
        ['patterns' => ['usuario_auth', 'usuario_id', 'mi_empresa/datos'], 'allow_authenticated' => true],
        ['methods' => ['GET'], 'patterns' => ['dashboard*'], 'any' => ['dashboard.view']],
        ['methods' => ['GET'], 'patterns' => ['rbac/roles/*'], 'any' => ['users.manage', 'users.permissions.manage']],
        ['patterns' => ['rbac*'], 'any' => ['users.permissions.manage']],
        ['patterns' => ['reporte*', 'reportes*', 'listado_arqueos'], 'any' => ['reports.generate']],
        ['patterns' => ['grupo*'], 'any' => ['users.roles.manage', 'users.permissions.manage', 'users.manage']],
        ['methods' => ['GET'], 'patterns' => ['usuario/grupo_usuario'], 'any' => ['users.roles.manage', 'users.manage', 'users.permissions.manage']],
        ['patterns' => ['usuario*'], 'any' => ['users.manage', 'users.permissions.manage']],
        ['patterns' => ['compra/anular'], 'any' => ['purchases.cancel']],
        ['patterns' => ['compra/modificar*'], 'any' => ['purchases.update']],
        ['patterns' => ['compra/guardar'], 'any' => ['purchases.create']],
        ['patterns' => ['compra*'], 'any' => ['purchases.create', 'purchases.view', 'purchases.payments']],
        ['patterns' => ['pago_compra*', 'pagos_proveedor*', 'c_x_pagar*'], 'any' => ['purchases.payments']],
        ['patterns' => ['venta/anular*'], 'any' => ['sales.cancel']],
        ['patterns' => ['venta/modificar*'], 'any' => ['sales.update']],
        ['patterns' => ['venta/guardar*'], 'any' => ['sales.create']],
        ['patterns' => ['venta*'], 'any' => ['sales.create', 'sales.view', 'sales.payments']],
        ['patterns' => ['pagos*', 'pago_*', 'c_x_cobrar*'], 'any' => ['sales.payments']],
        ['patterns' => ['arqueo*'], 'any' => ['cash.manage']],
        ['methods' => ['POST', 'PUT', 'PATCH', 'DELETE'], 'patterns' => ['articulo*'], 'any' => ['inventory.products.manage']],
        ['patterns' => ['articulo*'], 'any' => ['inventory.view', 'inventory.products.manage', 'purchases.create', 'sales.create']],
        ['patterns' => ['categoria*'], 'any' => ['inventory.categories.manage', 'inventory.products.manage']],
        ['patterns' => ['unidad*'], 'any' => ['inventory.presentations.manage', 'inventory.products.manage']],
        ['patterns' => ['marca*'], 'any' => ['inventory.lines.manage', 'inventory.products.manage']],
        ['patterns' => ['lote*'], 'any' => ['inventory.lots.manage', 'inventory.view', 'purchases.create', 'sales.create']],
        ['patterns' => ['ajuste*'], 'any' => ['inventory.adjustments.manage']],
        ['patterns' => ['motivo_gasto*'], 'any' => ['expenses.reasons.manage', 'expenses.manage']],
        ['patterns' => ['gasto*'], 'any' => ['expenses.manage']],
        ['patterns' => ['cliente*', 'clientes*'], 'any' => ['data.clients.manage', 'sales.create', 'sales.view', 'sales.payments']],
        ['patterns' => ['proveedor*'], 'any' => ['purchases.create', 'purchases.view', 'purchases.payments']],
        ['patterns' => ['personal*'], 'any' => ['data.personal.manage', 'users.manage']],
        ['patterns' => ['cargo*'], 'any' => ['data.positions.manage', 'data.personal.manage']],
        ['patterns' => ['mi_empresa*'], 'any' => ['data.company.manage']],
    ],
];
